ShopStore/Areas/Admin/Controllers/DashboardController.cs
using ShopStore.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopStore.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {

        //
        // GET: /Admin/Dashboard/
        [Authorize(Roles ="Admin")]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Orders()
        {
            StoreContext context = new StoreContext();
            return View(context.Orders);
        }
	}
}

ShopStore/Controllers/AuthorsController.cs
using ShopStore.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopStore.Controllers
{
    public class AuthorsController : Controller
    {
        StoreContext context = new StoreContext();

        // GET: Authors
        public ActionResult Index()
        {
            return View(context.Author.AsEnumerable());
        }
        public ActionResult Books(int id)
        {
            var res = context.Books.Where(x => x.AuthorId == id);
            return View(res);
        }
    }

}

ShopStore/Controllers/BooksController.cs
using ShopStore.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ShopStore.Controllers
{
    public class BooksController : Controller
    {
        ShopUserManager manager = new ShopUserManager();
        StoreContext context = new StoreContext();
        // GET: Books
        public ActionResult Index(string query = "", int AuthorId = 0)
        {
            ViewBag.Authors = context.Author.AsQueryable();

            var books = context.Books.AsQueryable();

            if (AuthorId != 0) {
                books = books.Where(x => x.AuthorId == AuthorId);
            }
            if (query != "") {
                books = books.Where(x => x.Name.Contains(query) || x.Description.Contains(query));
            }

            return View(books);
        }
        [Authorize]
        public async Task<HttpStatusCodeResult> Order(int id)
        {
            string username = User.Identity.Name;
            var user = await manager.FindByNameAsync(username);
            if (user == null)
            {
                return new HttpStatusCodeResult(500);
            }
            context.Orders.Add(new Entites.Models.Orders() {
                UserId = user.Id,
                bookId = id,
                Date = DateTime.Now
            });
            context.SaveChanges();
            return new HttpStatusCodeResult(HttpStatusCode.OK);

        }
    }
}

ShopStore/Areas/Admin/Views/Shared/_AdminShared.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>Star Admin</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="~/css/materialize.min.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/admin.style.css" rel="stylesheet" />

    <!-- javascript -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

    <script src="~/js/jquery.js"></script>
    <script src="~/js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {
            // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
            $('select').material_select();
            $('.modal').modal();
            $(document).find('label').each(function () {
                $(this).addClass("active");

            });

        });
        

        //General editing code
        function editClick(el) {
            event.preventDefault();
            var url = $(el).attr("href");
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    $("#Edit").empty();
                    $("#Edit").append($.parseHTML(data));
                    $("#Edit").modal('open');
                    $("#Edit").find('select').each(function () {
                        $(this).material_select();

                    });

                    $("#Edit").find('label').each(function () {
                        $(this).addClass("active");

                    });

                }
            });
        };
        //General Delete Code

        function deleteClick(el) {
            event.preventDefault();

            var url = $(el).attr("href");
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                 
                    $("#Delete").empty();

                    $("#Delete").append($.parseHTML(data));
                    $("#Delete").modal('open');

                    //var modelBodyContent = $(data).find("#deleteContent").html();
                    //var modelFooterContent = $(data).find("#DeleteButtons").html();
                    //$("#DeleteModel").find(".modal-body").html(modelBodyContent);
                    //$("#DeleteModel").find(".modal-footer").html(modelFooterContent);
                    //$("#DeleteModel").modal('show');
                }
            })
        };
        // General Details Code
        function detailsClick(el) {
            event.preventDefault();
            var url = $(el).attr("href");
            $.ajax({
                url: url,
                type: 'GET',
                success: function (data) {
                    $("#Details").empty();
                    $("#Details").append(data);
                    $("#Details").modal('open');

                }
            })
        };


    </script>


</head>
<body>

    <div class="row">
        <div class="left-side" id="left-side">
            <a href="#">
                <div class="prof">
                    <div class="row">
                        @*<div class="col s3">
                            <img src="/img/white-logo.png" class="responsive-img circle" />
                        </div>*@
                        <div class="col s10">
                            <p>AL STAR</p>
                        </div>
                        <div class="col s2">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                </div>
            </a>
            <div class="links">

                <ul>
                    @*<li class="li activee"><a href="@Url.Action("Default","Dashoard")"><i class="fa fa-dashboard"></i><span>Dashboard</span></a></li>*@
                    <ul class="collapsible" data-collapsible="accordion">
                        <li class="li"><a href="@Url.Action("index","Books")"><i class="material-icons">library_books</i><span>Books</span></a></li>
                     
                        <li class="li"><a href="@Url.Action("index","Authors")"><i class="material-icons">perm_identity</i><span>Authors</span></a></li>
                        <li class="li"><a href="@Url.Action("Orders","Dashboard")"><i class="material-icons"> done_all</i><span>Orders</span></a></li>

                    </ul>

                </ul>
            </div>
        </div>
        <div class="right-side">
            <nav>
                <div class="nav-wrapper">
                    @*<a href="#">
                            <img src="~/img/logo revera.jpg" class="responsive-img logo" />
                        </a>*@
                    <ul class="right">
                        <li class="log"><a href="/home/Logout"><i class="fa fa-power-off"></i></a></li>
                    </ul>
                </div>
            </nav>

            <div style="margin-top: 100px">
                @RenderBody()
            </div>

        </div>
    </div>


    <script src="/js/mainadmin.js"></script>

</body>
</html>